SET NAMES utf8mb4;
SET CHARACTER SET utf8mb4;

SELECT 'TABLE_COMMENTS' as info;
SELECT TABLE_NAME, TABLE_COMMENT 
FROM information_schema.TABLES 
WHERE TABLE_SCHEMA = DATABASE() 
AND TABLE_NAME LIKE 'scm_%' 
ORDER BY TABLE_NAME;
