SET NAMES utf8mb4;
SET CHARACTER SET utf8mb4;

ALTER TABLE scm_supplier MODIFY COLUMN `ext1` VARCHAR(255) COMMENT '预留扩展字段1';
ALTER TABLE scm_supplier MODIFY COLUMN `ext2` VARCHAR(255) COMMENT '预留扩展字段2';
ALTER TABLE scm_supplier MODIFY COLUMN `ext3` VARCHAR(255) COMMENT '预留扩展字段3';

SELECT TABLE_NAME, COLUMN_NAME, COLUMN_COMMENT 
FROM information_schema.COLUMNS 
WHERE TABLE_SCHEMA = DATABASE() 
AND TABLE_NAME = 'scm_supplier' 
AND COLUMN_NAME IN ('ext1', 'ext2', 'ext3');
